services:
  db:
    image: mysql:8.0
    container_name: paw_match_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pawmatch_root
      MYSQL_USER: pawmatch
      MYSQL_PASSWORD: pawmatch
      MYSQL_DATABASE: paw_match
    ports:
      - "3306:3306"
    volumes:
      - paw_match_db_data:/var/lib/mysql

volumes:
  paw_match_db_data:
